spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hasanalmunawar01@gmail.com
    password: vhpmeizmdpvpiclz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true